import { PrismaClient, ProductType, Role } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  const existingAdmin = await prisma.user.findUnique({
    where: { email: 'admin@admin.com' },
  });

  if (!existingAdmin) {
    const hashedPassword = await bcrypt.hash('admin123', 10);

    const admin = await prisma.user.create({
      data: {
        email: 'admin@admin.com',
        password: hashedPassword,
        firstName: 'Admin',
        lastName: 'User',
        role: Role.ADMIN,
        isActive: true,
      },
    });

    console.log('Admin user created:', admin);
  } else {
    console.log('Admin user already exists');
  }

  const brandsData = [
    {
      id: '1',
      name: 'Lenovo',
      description: 'Hewlett-Packard Company',
    },
    {
      id: '2',
      name: 'Dell',
      description: 'Dell Technologies',
    },
    {
      id: '3',
      name: 'Logitech',
      description: 'Computer peripherals and software',
    },
    {
      id: '4',
      name: 'AMD',
      description: 'Advanced Micro Devices - Processors and Graphics Cards',
    },
    {
      id: '5',
      name: 'Intel',
      description: 'Processors and Computing Innovation',
    },
    {
      id: '6',
      name: 'NVIDIA',
      description: 'Graphics Processing Units and AI Computing',
    },
    {
      id: '7',
      name: 'ASUS',
      description: 'Computer Hardware and Consumer Electronics',
    },
    {
      id: '8',
      name: 'MSI',
      description: 'Computer Hardware and Gaming Equipment',
    },
    {
      id: '9',
      name: 'Corsair',
      description: 'PC Components and Gaming Peripherals',
    },
    {
      id: '10',
      name: 'GIGABYTE',
      description: 'Computer Hardware and Components',
    },
    {
      id: '11',
      name: 'Western Digital',
      description: 'Data Storage Solutions',
    },
    {
      id: '12',
      name: 'Seagate',
      description: 'Data Storage Technology',
    },
    {
      id: '13',
      name: 'Kingston',
      description: 'Memory and Storage Products',
    },
    {
      id: '14',
      name: 'G.Skill',
      description: 'High-Performance Memory Products',
    },
    {
      id: '15',
      name: 'EVGA',
      description: 'Graphics Cards and Power Supplies',
    },
    {
      id: '16',
      name: 'be quiet!',
      description: 'Premium PC Components',
    },
  ];

  const brands = await Promise.all(
    brandsData.map(async (brand) => {
      const existingBrand = await prisma.brand.findFirst({
        where: { name: brand.name },
      });
      if (!existingBrand) {
        return prisma.brand.create({
          data: {
            id: brand.id,
            name: brand.name,
            description: brand.description,
          },
        });
      }
      return existingBrand;
    }),
  );

  const categoryData = [
    {
      id: '1',
      name: 'Laptops',
      description: 'Portable computers',
      slug: 'laptops',
    },
    {
      id: '2',
      name: 'Alienware Laptops',
      description: 'High-performance gaming laptops',
      slug: 'alienware-laptops',
      parentName: 'Laptops',
    },
    {
      id: '3',
      name: 'G Series Laptops',
      description: 'Gaming laptops with powerful performance',
      slug: 'g-series-laptops',
      parentName: 'Laptops',
    },
    {
      id: '4',
      name: 'Chromebook Laptops',
      description: 'Chrome OS-based lightweight laptops',
      slug: 'chromebook-laptops',
      parentName: 'Laptops',
    },
    {
      id: '5',
      name: 'Inspiron Laptops',
      description: 'Versatile laptops for everyday computing',
      slug: 'inspiron-laptops',
      parentName: 'Laptops',
    },
    {
      id: '6',
      name: 'Components',
      description: 'Computer parts and components',
      slug: 'components',
    },
    {
      id: '7',
      name: 'Accessories',
      description: 'Computer peripherals and accessories',
      slug: 'accessories',
    },
    {
      id: '8',
      name: 'Processors',
      description: 'CPUs and processors',
      slug: 'processors',
    },
    {
      id: '9',
      name: 'Motherboards',
      description: 'Computer motherboards',
      slug: 'motherboards',
    },
    {
      id: '10',
      name: 'Memory',
      description: 'RAM and memory modules',
      slug: 'memory',
    },
    {
      id: '11',
      name: 'Storage',
      description: 'Hard drives and SSDs',
      slug: 'storage',
    },
    {
      id: '12',
      name: 'Graphics Cards',
      description: 'GPUs and video cards',
      slug: 'graphics-cards',
    },
    {
      id: '13',
      name: 'Power Supplies',
      description: 'PSU and power supplies',
      slug: 'power-supplies',
    },
    {
      id: '14',
      name: 'Cases',
      description: 'Computer cases and chassis',
      slug: 'cases',
    },
    {
      id: '15',
      name: 'Monitors',
      description: 'Computer displays and monitors',
      slug: 'monitors',
    },
    {
      id: '16',
      name: 'Printers',
      description: 'Printers and scanners',
      slug: 'printers',
    },
    {
      id: '17',
      name: 'All-in-One PCs',
      description: 'Integrated desktop computers',
      slug: 'all-in-one-pcs',
    },
    {
      id: '18',
      name: 'Desktops',
      description: 'Desktop computers',
      slug: 'desktops',
    },
  ];

  const categories = await Promise.all(
    categoryData
      .filter((cat) => !cat['parentName'])
      .map(async (cat) => {
        const existingCategory = await prisma.category.findFirst({
          where: { name: cat.name },
        });
        if (!existingCategory) {
          return prisma.category.create({
            data: {
              id: cat.id,
              name: cat.name,
              description: cat.description,
              slug: cat.slug,
            },
          });
        }
        return existingCategory;
      }),
  );

  const childCategories = await Promise.all(
    categoryData
      .filter((cat) => cat['parentName'])
      .map(async (cat) => {
        const existingCategory = await prisma.category.findFirst({
          where: { name: cat.name },
        });

        if (!existingCategory) {
          const parentCategory = await prisma.category.findFirst({
            where: { name: cat['parentName'] },
          });

          return prisma.category.create({
            data: {
              name: cat.name,
              description: cat.description,
              slug: cat.slug,
              parentId: parentCategory.id,
            },
          });
        }
        return existingCategory;
      }),
  );

  const allCategories = [...categories, ...childCategories];

  // const productsData = [
  //   {
  //     name: 'HP Pavilion 15',
  //     description: 'Powerful and sleek laptop for everyday computing',
  //     type: ProductType.LAPTOP,
  //     categoryId: allCategories[0].id,
  //     brandId: brands[0].id,
  //     price: 899.99,
  //     salePrice: 849.99,
  //     stock: 30,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i5-12500H',
  //       memory: '16GB DDR4',
  //       storage: '512GB NVMe SSD',
  //       display_size: '15.6" FHD IPS Anti-glare',
  //       graphics: 'Intel Iris Xe Graphics',
  //       battery: '45Wh',
  //       weight: '1.75 kg',
  //       os: 'Windows 11 Home',
  //     },
  //     images: [
  //       'https://www.zdnet.com/a/img/resize/d52af392718425c7444c98867d4200e23790eacd/2024/08/05/14e2e048-1cc4-4561-8a50-4636f1ee74f6/dell-xps-14-1.jpg?auto=webp&fit=crop&height=900&width=1200',
  //       'https://btech.com/media/catalog/product/cache/0799860a5482475be817e961d428f0bc/h/p/hp-victus-16-e1011ne-gaming-amd-512gb-16gb-blue.jpg',
  //       'https://in-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/c/0/c08192495_1_5_4.png',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_MZXj-9Uox6ulRj9WjNGTaZ1vCOl3fQqHAKigBLevu3RZF7Qxs21achJ16TzrWIacESg&usqp=CAU',
  //     ],
  //   },
  //   {
  //     name: 'Dell XPS 13 Plus',
  //     description: 'Premium ultrabook with cutting-edge design',
  //     type: ProductType.LAPTOP,
  //     categoryId: allCategories[10].id,
  //     brandId: brands[1].id,
  //     price: 1499.99,
  //     salePrice: 1399.99,
  //     stock: 20,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i7-12700H',
  //       memory: '16GB LPDDR5',
  //       storage: '1TB NVMe SSD',
  //       display_size: '13.4" 4K UHD+ Touch',
  //       graphics: 'Intel Iris Xe Graphics',
  //       battery: '55Wh',
  //       weight: '1.24 kg',
  //       os: 'Windows 11 Pro',
  //     },
  //     images: [
  //       'https://www.zdnet.com/a/img/resize/d52af392718425c7444c98867d4200e23790eacd/2024/08/05/14e2e048-1cc4-4561-8a50-4636f1ee74f6/dell-xps-14-1.jpg?auto=webp&fit=crop&height=900&width=1200',
  //       'https://btech.com/media/catalog/product/cache/0799860a5482475be817e961d428f0bc/h/p/hp-victus-16-e1011ne-gaming-amd-512gb-16gb-blue.jpg',
  //       'https://in-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/c/0/c08192495_1_5_4.png',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_MZXj-9Uox6ulRj9WjNGTaZ1vCOl3fQqHAKigBLevu3RZF7Qxs21achJ16TzrWIacESg&usqp=CAU',
  //     ],
  //   },
  //   {
  //     name: 'Lenovo ThinkPad X1 Carbon Gen 10',
  //     description: 'Business laptop with premium build quality',
  //     price: 1799.99,
  //     salePrice: 1699.99,
  //     stock: 15,
  //     type: ProductType.LAPTOP,
  //     categoryId: allCategories[11].id,
  //     brandId: brands[0].id,

  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i7-1260P',
  //       memory: '32GB LPDDR5',
  //       storage: '1TB PCIe SSD',
  //       display_size: '14" WQUXGA IPS Anti-glare',
  //       graphics: 'Intel Iris Xe Graphics',
  //       battery: '57Wh',
  //       weight: '1.12 kg',
  //       os: 'Windows 11 Pro',
  //     },
  //     images: [
  //       'https://www.zdnet.com/a/img/resize/d52af392718425c7444c98867d4200e23790eacd/2024/08/05/14e2e048-1cc4-4561-8a50-4636f1ee74f6/dell-xps-14-1.jpg?auto=webp&fit=crop&height=900&width=1200',
  //       'https://btech.com/media/catalog/product/cache/0799860a5482475be817e961d428f0bc/h/p/hp-victus-16-e1011ne-gaming-amd-512gb-16gb-blue.jpg',
  //       'https://in-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/c/0/c08192495_1_5_4.png',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_MZXj-9Uox6ulRj9WjNGTaZ1vCOl3fQqHAKigBLevu3RZF7Qxs21achJ16TzrWIacESg&usqp=CAU',
  //     ],
  //   },
  //   {
  //     name: 'ASUS ROG Zephyrus G14',
  //     description: 'Powerful gaming laptop in compact form factor',
  //     price: 1699.99,
  //     salePrice: 1599.99,
  //     stock: 25,
  //     type: ProductType.LAPTOP,
  //     categoryId: allCategories[12].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'AMD Ryzen 9 6900HS',
  //       memory: '32GB DDR5',
  //       storage: '1TB NVMe SSD',
  //       display_size: '14" QHD 165Hz',
  //       graphics: 'NVIDIA RTX 3060 6GB',
  //       battery: '76Wh',
  //       weight: '1.65 kg',
  //       os: 'Windows 11 Home',
  //     },
  //     images: [
  //       'https://www.zdnet.com/a/img/resize/d52af392718425c7444c98867d4200e23790eacd/2024/08/05/14e2e048-1cc4-4561-8a50-4636f1ee74f6/dell-xps-14-1.jpg?auto=webp&fit=crop&height=900&width=1200',
  //       'https://btech.com/media/catalog/product/cache/0799860a5482475be817e961d428f0bc/h/p/hp-victus-16-e1011ne-gaming-amd-512gb-16gb-blue.jpg',
  //       'https://in-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/c/0/c08192495_1_5_4.png',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_MZXj-9Uox6ulRj9WjNGTaZ1vCOl3fQqHAKigBLevu3RZF7Qxs21achJ16TzrWIacESg&usqp=CAU',
  //     ],
  //   },
  //   {
  //     name: 'MSI Creator Z16',
  //     description: 'Professional laptop for content creators',
  //     price: 2299.99,
  //     salePrice: 2099.99,
  //     stock: 10,
  //     featured: true,
  //     isPublished: true,
  //     type: ProductType.LAPTOP,
  //     categoryId: allCategories[0].id,
  //     brandId: brands[7].id,
  //     specs: {
  //       processor: 'Intel Core i9-12900H',
  //       memory: '64GB DDR5',
  //       storage: '2TB NVMe SSD',
  //       display_size: '16" QHD+ Touch 165Hz',
  //       graphics: 'NVIDIA RTX 3080 8GB',
  //       battery: '90Wh',
  //       weight: '2.2 kg',
  //       os: 'Windows 11 Pro',
  //     },
  //     images: [
  //       'https://www.zdnet.com/a/img/resize/d52af392718425c7444c98867d4200e23790eacd/2024/08/05/14e2e048-1cc4-4561-8a50-4636f1ee74f6/dell-xps-14-1.jpg?auto=webp&fit=crop&height=900&width=1200',
  //       'https://btech.com/media/catalog/product/cache/0799860a5482475be817e961d428f0bc/h/p/hp-victus-16-e1011ne-gaming-amd-512gb-16gb-blue.jpg',
  //       'https://in-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/c/0/c08192495_1_5_4.png',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_MZXj-9Uox6ulRj9WjNGTaZ1vCOl3fQqHAKigBLevu3RZF7Qxs21achJ16TzrWIacESg&usqp=CAU',
  //     ],
  //   },
  //   {
  //     name: 'Logitech MX Master 3',
  //     description: 'Advanced wireless mouse for productivity',
  //     price: 99.99,
  //     type: ProductType.ACCESSORY,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     salePrice: 89.99,
  //     stock: 50,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       connectivity: 'Wireless',
  //       battery_life: '70 days',
  //       dpi: '4000',
  //       buttons: 7,
  //     },
  //     images: [
  //       'https://resource.logitech.com/content/dam/logitech/en/products/mice/mx-master-3s/gallery/mx-master-3s-mouse-top-view-graphite.png',
  //       'https://images-cdn.ubuy.co.in/6346e368d3e4ef5797301c42-logitech-mx-master-3-mouse-nirkabel.jpg',
  //     ],
  //   },
  //   {
  //     name: 'AMD Ryzen 9 7950X',
  //     description: 'High-end desktop processor with 16 cores and 32 threads',
  //     price: 699.99,
  //     salePrice: 649.99,
  //     stock: 15,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       cores: 16,
  //       threads: 32,
  //       base_speed: '4.5 GHz',
  //       boost_speed: '5.7 GHz',
  //       cache: '80MB',
  //       tdp: '170W',
  //       socket: 'AM5',
  //     },
  //     type: ProductType.PROCESSOR,
  //     categoryId: allCategories[3].id,
  //     brandId: brands[3].id,
  //     images: [
  //       'https://m.media-amazon.com/images/I/5116zdA9uyL.jpg',
  //       'https://m.media-amazon.com/images/I/5116zdA9uyL.jpg',
  //       'https://m.media-amazon.com/images/I/5116zdA9uyL.jpg',
  //       'https://m.media-amazon.com/images/I/5116zdA9uyL.jpg',
  //     ],
  //   },
  //   {
  //     name: 'Intel Core i9-13900K',
  //     description:
  //       'High-performance desktop processor with 24 cores and 32 threads',
  //     type: ProductType.PROCESSOR,
  //     categoryId: allCategories[3].id,
  //     brandId: brands[4].id,
  //     images: [
  //       'https://m.media-amazon.com/images/I/61My4F2-XUL.jpg',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUmE4Cj9Cv-J6fo0yG1GwRsjB2G45pKRQUy5XCsaDPaZ87lOUstfuK-yYOmybQXCaapf4&usqp=CAU',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1ithArLEiabRVHdj7N9t2-s9cDnGmYmNMeg&s',
  //     ],
  //     price: 589.99,
  //     salePrice: 549.99,
  //     stock: 20,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       cores: 24,
  //       threads: 32,
  //       base_speed: '3.0 GHz',
  //       boost_speed: '5.8 GHz',
  //       cache: '36MB',
  //       tdp: '125W',
  //       socket: 'LGA 1700',
  //     },
  //   },
  //   {
  //     name: 'ASUS ROG Strix X670E-E Gaming',
  //     description: 'High-end AMD AM5 motherboard with PCIe 5.0 support',
  //     price: 499.99,
  //     salePrice: 469.99,
  //     stock: 10,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       socket: 'AM5',
  //       form_factor: 'ATX',
  //       memory_slots: 4,
  //       max_memory: '128GB',
  //       pci_slots: '3x PCIe 5.0 x16',
  //       wifi: 'WiFi 6E',
  //       bluetooth: '5.2',
  //     },
  //     type: ProductType.MOTHERBOARD,
  //     categoryId: allCategories[4].id,
  //     brandId: brands[6].id,
  //     images: [
  //       'https://dlcdnwebimgs.asus.com/gain/ECBF5DA1-F9D1-4F29-9A4E-6F7F35BC1D4D/w717/h525',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTelhhl9S70D8AsAuRF9kq6vsc0q4Ug22F2y-YyGcvspMJobWwUhe65c11jK0ed2TC1FNY&usqp=CAU',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1ithArLEiabRVHdj7N9t2-s9cDnGmYmNMeg&s',
  //     ],
  //   },
  //   {
  //     name: 'Dell S2721QS',
  //     description: '27-inch 4K IPS Monitor',
  //     price: 399.99,
  //     salePrice: 349.99,
  //     stock: 30,
  //     type: ProductType.MONITOR,
  //     categoryId: allCategories[14].id,
  //     brandId: brands[1].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       display_size: '27 inch',
  //       resolution: '3840 x 2160',
  //       refresh_rate: '60 Hz',
  //       panel_type: 'IPS',
  //       response: '4ms',
  //       hdr: 'HDR10',
  //     },
  //     images: [
  //       'https://i.dell.com/is/image/DellContent//content/dam/images/products/electronics-and-accessories/dell/monitors/s-series/s2721qs/s2721qs-cfp-00000ff090-gy.psd?fmt=pjpg&pscan=auto&scl=1&wid=3872&hei=3060&qlt=100,1&resMode=sharp2&size=3872,3060&chrss=full&imwidth=5000',

  //       'https://i.dell.com/is/image/DellContent//content/dam/images/products/electronics-and-accessories/dell/monitors/s-series/s2721qs/s2721qs-cfp-00000ff090-gy.psd?fmt=pjpg&pscan=auto&scl=1&wid=3872&hei=3060&qlt=100,1&resMode=sharp2&size=3872,3060&chrss=full&imwidth=5000',

  //       'https://i.dell.com/is/image/DellContent//content/dam/images/products/electronics-and-accessories/dell/monitors/s-series/s2721qs/s2721qs-cfp-00000ff090-gy.psd?fmt=pjpg&pscan=auto&scl=1&wid=3872&hei=3060&qlt=100,1&resMode=sharp2&size=3872,3060&chrss=full&imwidth=5000',
  //     ],
  //   },
  //   {
  //     name: 'LG 34WN80C-B',
  //     description: '34-inch UltraWide Monitor',
  //     price: 699.99,
  //     salePrice: 649.99,
  //     stock: 20,
  //     type: ProductType.MONITOR,
  //     categoryId: allCategories[14].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       display_size: '34 inch',
  //       resolution: '3440 x 1440',
  //       refresh_rate: '75 Hz',
  //       panel_type: 'IPS',
  //       response: '5ms',
  //       curved: 'Yes',
  //     },
  //     images: [
  //       'https://www.lg.com/us/images/monitors/md07000140/gallery/desktop-01.jpg',
  //     ],
  //   },
  //   {
  //     name: 'HP LaserJet Pro M404dn',
  //     description: 'Monochrome Laser Printer',
  //     price: 299.99,
  //     salePrice: 279.99,
  //     stock: 25,
  //     type: ProductType.PRINTER,
  //     categoryId: allCategories[15].id,
  //     brandId: brands[0].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       type: 'Laser',
  //       color: 'Monochrome',
  //       ppm: '40',
  //       dpi: '1200 x 1200',
  //       duplex: 'Automatic',
  //       paper_size: 'A4/Letter',
  //     },
  //     images: [],
  //   },
  //   {
  //     name: 'Epson EcoTank ET-4760',
  //     description: 'All-in-One Supertank Printer',
  //     price: 499.99,
  //     salePrice: 449.99,
  //     stock: 15,
  //     type: ProductType.PRINTER,
  //     categoryId: allCategories[15].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       type: 'Inkjet',
  //       color: 'Color',
  //       ink_system: '8-color dye based',
  //       max_paper_size: 'A3+',
  //       borderless: 'Yes',
  //     },
  //     images: [
  //       'https://m.media-amazon.com/images/I/81dR5XQnLtL.jpg',
  //       'https://m.media-amazon.com/images/I/81dR5XQnLtL.jpg',
  //       'https://m.media-amazon.com/images/I/81dR5XQnLtL.jpg',
  //       'https://m.media-amazon.com/images/I/81dR5XQnLtL.jpg',
  //     ],
  //   },
  //   {
  //     name: 'HP Envy 34" All-in-One',
  //     description: 'Premium All-in-One Desktop PC',
  //     price: 1999.99,
  //     salePrice: 1899.99,
  //     stock: 10,
  //     type: ProductType.DESKTOP,
  //     categoryId: allCategories[16].id,
  //     brandId: brands[0].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i7-11700',
  //       memory: '32GB DDR4',
  //       storage: '1TB SSD',
  //       display_size: '34" 5K',
  //       graphics: 'NVIDIA RTX 3060',
  //       webcam: '16MP',
  //       os: 'Windows 11 Home',
  //     },
  //     images: [
  //       'https://images-cdn.ubuy.co.in/633fecb2cc5a1642c963740b-hp-envy-34-desktop-1tb-ssd-128gb-ram.jpg',
  //       'https://images-cdn.ubuy.co.in/633fecb2cc5a1642c963740b-hp-envy-34-desktop-1tb-ssd-128gb-ram.jpg',
  //       'https://images-cdn.ubuy.co.in/633fecb2cc5a1642c963740b-hp-envy-34-desktop-1tb-ssd-128gb-ram.jpg',
  //       'https://images-cdn.ubuy.co.in/633fecb2cc5a1642c963740b-hp-envy-34-desktop-1tb-ssd-128gb-ram.jpg',
  //     ],
  //   },
  //   {
  //     name: 'Dell XPS Desktop',
  //     description: 'High-Performance Desktop PC',
  //     price: 1499.99,
  //     salePrice: 1399.99,
  //     stock: 20,
  //     type: ProductType.DESKTOP,
  //     categoryId: allCategories[17].id,
  //     brandId: brands[1].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i9-12900K',
  //       memory: '64GB DDR5',
  //       storage: '2TB SSD + 2TB HDD',
  //       graphics: 'NVIDIA RTX 3080',
  //       power_supply: '750W',
  //       os: 'Windows 11 Pro',
  //     },
  //     images: [
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDxeMii0quUrAdJY7Z3EVPBlxTzYRlZXkE0g&s',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDxeMii0quUrAdJY7Z3EVPBlxTzYRlZXkE0g&s',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDxeMii0quUrAdJY7Z3EVPBlxTzYRlZXkE0g&s',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDxeMii0quUrAdJY7Z3EVPBlxTzYRlZXkE0g&s',
  //     ],
  //   },
  //   {
  //     name: 'Corsair K95 RGB Platinum',
  //     description: 'Mechanical Gaming Keyboard',
  //     price: 199.99,
  //     salePrice: 179.99,
  //     stock: 40,
  //     type: ProductType.KEYBOARD,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       switches: 'Cherry MX Speed',
  //       backlight: 'RGB',
  //       macro: '6 Keys',
  //       palmrest: 'Detachable',
  //       multimedia: 'Yes',
  //       usb: 'USB 3.0 Passthrough',
  //     },
  //     images: [
  //       'https://m.media-amazon.com/images/I/7193Jl8PejL._AC_UF1000,1000_QL80_.jpg',
  //       'https://m.media-amazon.com/images/I/7193Jl8PejL._AC_UF1000,1000_QL80_.jpg',
  //       'https://m.media-amazon.com/images/I/7193Jl8PejL._AC_UF1000,1000_QL80_.jpg',
  //       'https://m.media-amazon.com/images/I/7193Jl8PejL._AC_UF1000,1000_QL80_.jpg',
  //     ],
  //   },
  //   {
  //     name: 'ASUS ROG Swift PG279QM',
  //     description: '27-inch Gaming Monitor',
  //     price: 849.99,
  //     salePrice: 799.99,
  //     stock: 25,
  //     type: ProductType.MONITOR,
  //     categoryId: allCategories[14].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       display_size: '27 inch',
  //       resolution: '2560 x 1440',
  //       refresh_rate: '240 Hz',
  //       panel_type: 'IPS',
  //       ports: 'HDMI 2.1, DisplayPort 1.4',
  //       hdr: 'HDR400',
  //     },
  //     images: [
  //       'https://dlcdnrog.asus.com/rog/media/1610267604142.webp',
  //       'https://dlcdnrog.asus.com/rog/media/1610267604142.webp',
  //       'https://dlcdnrog.asus.com/rog/media/1610267604142.webp',
  //       'https://dlcdnrog.asus.com/rog/media/1610267604142.webp',
  //     ],
  //   },
  //   {
  //     name: 'Samsung Odyssey G9',
  //     description: '49-inch Super Ultra-wide Gaming Monitor',
  //     price: 1499.99,
  //     salePrice: 1399.99,
  //     stock: 15,
  //     type: ProductType.MONITOR,
  //     categoryId: allCategories[14].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       display_size: '49 inch',
  //       resolution: '5120 x 1440',
  //       refresh_rate: '240 Hz',
  //       panel_type: 'VA',
  //       response: '1ms',
  //       hdr: 'HDR1000',
  //       curved: 'Yes',
  //     },
  //     images: [
  //       'https://img.global.news.samsung.com/uk/wp-content/uploads/2020/06/Odyssey-G9_2.jpg',
  //       'https://img.global.news.samsung.com/uk/wp-content/uploads/2020/06/Odyssey-G9_2.jpg',
  //       'https://img.global.news.samsung.com/uk/wp-content/uploads/2020/06/Odyssey-G9_2.jpg',
  //       'https://img.global.news.samsung.com/uk/wp-content/uploads/2020/06/Odyssey-G9_2.jpg',
  //     ],
  //   },
  //   {
  //     name: 'Brother MFC-L8900CDW',
  //     description: 'Color Laser All-in-One Printer',
  //     price: 799.99,
  //     salePrice: 749.99,
  //     stock: 20,
  //     type: ProductType.PRINTER,
  //     categoryId: allCategories[15].id,
  //     brandId: brands[1].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       type: 'Laser',
  //       color: 'Color',
  //       ppm: '33',
  //       dpi: '2400 x 600',
  //       duplex: 'Automatic',
  //       scanner: 'Yes',
  //       fax: 'Yes',
  //     },
  //     images: [
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8VSlKYjJnyvcLiGxLRdFmvOl4aIctPNO0KA&s',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQb5oO-vWFAktvaZYCit9IVb3JqjudWMB9dvQ&s',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQb5oO-vWFAktvaZYCit9IVb3JqjudWMB9dvQ&s',
  //     ],
  //   },
  //   {
  //     name: 'Canon PIXMA Pro-200',
  //     description: 'Professional Photo Printer',
  //     price: 599.99,
  //     salePrice: 549.99,
  //     stock: 15,
  //     type: ProductType.PRINTER,
  //     categoryId: allCategories[15].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       type: 'Inkjet',
  //       color: 'Color',
  //       ink_system: '8-color dye based',
  //       max_paper_size: 'A3+',
  //       borderless: 'Yes',
  //       resolution: '4800 x 2400 dpi',
  //     },
  //     images: [
  //       'https://m.media-amazon.com/images/I/61mma6Ydw4L.jpg',
  //       'https://m.media-amazon.com/images/I/61KJsq1oucL.jpg',
  //       'https://in.canon/media/image/2020/10/12/e33926f20bd64ca196a9251d4f89f04b_ProL_SIS_LCD_en-570x400.png',
  //     ],
  //   },
  //   {
  //     name: 'Microsoft Surface Studio 2+',
  //     description: 'Premium Creative All-in-One PC',
  //     price: 4499.99,
  //     salePrice: 4299.99,
  //     stock: 10,
  //     type: ProductType.ALL_IN_ONE,
  //     categoryId: allCategories[16].id,
  //     brandId: brands[0].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i7-11370H',
  //       memory: '32GB DDR4',
  //       storage: '1TB SSD',
  //       display_size: '28" PixelSense Touch',
  //       graphics: 'NVIDIA RTX 3060',
  //       resolution: '4500 x 3000',
  //       os: 'Windows 11 Pro',
  //     },
  //     images: [
  //       'https://images-cdn.ubuy.co.in/651c3fd774f53a1c6c7ac265-microsoft-surface-laptop-studio-2-2023.jpg',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrnF8DTC92PrtLje9ZbMuYZNPxEsfqp05Y7xTvr-z5XF2uD3VJ605mmmyl98U11UjWW9o&usqp=CAU',
  //       'https://m.media-amazon.com/images/I/619z6M48PrL._AC_UF1000,1000_QL80_.jpg',
  //     ],
  //   },
  //   {
  //     name: 'Lenovo Yoga AIO 7',
  //     description: 'Versatile All-in-One PC',
  //     price: 1699.99,
  //     salePrice: 1599.99,
  //     stock: 15,
  //     type: ProductType.ALL_IN_ONE,
  //     categoryId: allCategories[16].id,
  //     brandId: brands[0].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'AMD Ryzen 7 5800H',
  //       memory: '16GB DDR4',
  //       storage: '1TB SSD',
  //       display_size: '27" 4K IPS Touch',
  //       graphics: 'AMD Radeon RX 6600M',
  //       rotatable: 'Yes',
  //       os: 'Windows 11 Home',
  //     },
  //     images: [
  //       'https://p2-ofp.static.pub/fes/cms/2023/03/21/praagjgjkw7n2q8yig3ly57natozkg002850.png',
  //       'https://p2-ofp.static.pub/fes/cms/2023/03/21/praagjgjkw7n2q8yig3ly57natozkg002850.png',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScbyyeMgX152gcHFgsk0vNz0mPv7_6IDUOUZJjHqu_0we8p7rUjRrdwl5zjmuc94dlrxU&usqp=CAU',
  //     ],
  //   },
  //   {
  //     name: 'HP OMEN 45L',
  //     description: 'High-End Gaming Desktop',
  //     price: 2999.99,
  //     salePrice: 2799.99,
  //     stock: 12,
  //     type: ProductType.DESKTOP,
  //     categoryId: allCategories[17].id,
  //     brandId: brands[0].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i9-12900K',
  //       memory: '64GB DDR5',
  //       storage: '2TB NVMe SSD + 2TB HDD',
  //       graphics: 'NVIDIA RTX 3090',
  //       cooling: 'Cryo Chamber',
  //       power_supply: '800W 80+ Platinum',
  //       os: 'Windows 11 Pro',
  //     },
  //     images: [
  //       'https://www.omen.com/content/dam/sites/omen/worldwide/desktops/omen-40l/omen-45l/omen-45-l-2/articuno-1.png',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxzsOqXnoYg9l2Qc1ranLvwBNf9pzbdXsKhHcQuC1bcHYDK7h8WqY--kEMACYxALfGlnU&usqp=CAU',
  //       'https://www.omen.com/content/dam/sites/omen/worldwide/desktops/omen-40l/omen-45l/omen-45-l-2/articuno-2.png',
  //     ],
  //   },
  //   {
  //     name: 'Logitech G Pro X Wireless',
  //     description: 'Professional Gaming Headset',
  //     price: 199.99,
  //     salePrice: 179.99,
  //     stock: 35,
  //     type: ProductType.ACCESSORY,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       type: 'Over-ear',
  //       wireless: 'Yes',
  //       battery_life: '20 hours',
  //       microphone: 'Detachable',
  //       surround: 'DTS Headphone:X 2.0',
  //       connectivity: '2.4 GHz wireless',
  //     },
  //     images: [
  //       'https://compumise.in/wp-content/uploads/2023/03/pro-headset-gallery-1-2.webp',
  //       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpDAucXoxSADF6arvnqyMy7DM4cauC8wG7CGxnCad0BKg_WSBiyTUuJ-QPz2CKSqK9abQ&usqp=CAU',
  //       'https://www.tanotis.com/cdn/shop/files/1684885699_IMG_1989293_800x.jpg?v=1707324202',
  //     ],
  //   },
  //   {
  //     name: 'Corsair Vengeance LPX 32GB',
  //     description: 'High-performance DDR4 RAM kit',
  //     price: 149.99,
  //     salePrice: 139.99,
  //     stock: 30,
  //     type: ProductType.RAM,
  //     categoryId: allCategories[3].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       capacity: '32GB (2x16GB)',
  //       type: 'DDR4',
  //       speed: '3600MHz',
  //       latency: 'CL18',
  //       voltage: '1.35V',
  //       heat_spreader: 'Aluminum',
  //     },
  //     images: [
  //       'https://m.media-amazon.com/images/I/61uWHA2E5eL._AC_UF1000,1000_QL80_.jpg',
  //       'https://images-cdn.ubuy.co.in/634f34037263b74cb645a442-corsair-vengeance-lpx-32gb-2-x-16gb.jpg',
  //       'https://m.media-amazon.com/images/I/61uWHA2E5eL._AC_UF1000,1000_QL80_.jpg',
  //       'https://images-cdn.ubuy.co.in/634f34037263b74cb645a442-corsair-vengeance-lpx-32gb-2-x-16gb.jpg',
  //     ],
  //   },
  //   {
  //     name: 'G.SKILL Trident Z5 RGB 32GB',
  //     description: 'Premium DDR5 RAM with RGB',
  //     price: 219.99,
  //     salePrice: 199.99,
  //     stock: 25,
  //     type: ProductType.RAM,
  //     categoryId: allCategories[3].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       capacity: '32GB (2x16GB)',
  //       type: 'DDR5',
  //       speed: '6000MHz',
  //       latency: 'CL36',
  //       voltage: '1.35V',
  //       rgb: 'Yes',
  //     },
  //     images: [
  //       'https://m.media-amazon.com/images/I/51tyNdXDcDL._AC_UF1000,1000_QL80_.jpg',
  //       'https://www.vedantcomputers.com/image/cache/catalog/assets/product/g-skill/ram/f5-6000j3040f16gx2-tz5rs/f5-6000j3040f16gx2-tz5rs-2-550x550.jpg',
  //       'https://m.media-amazon.com/images/I/51tyNdXDcDL._AC_UF1000,1000_QL80_.jpg',
  //       'https://www.vedantcomputers.com/image/cache/catalog/assets/product/g-skill/ram/f5-6000j3040f16gx2-tz5rs/f5-6000j3040f16gx2-tz5rs-2-550x550.jpg',
  //     ],
  //   },
  //   {
  //     name: 'Samsung 980 PRO 2TB',
  //     description: 'PCIe 4.0 NVMe SSD',
  //     price: 299.99,
  //     salePrice: 279.99,
  //     stock: 40,
  //     type: ProductType.SSD,
  //     categoryId: allCategories[4].id,
  //     brandId: brands[5].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       capacity: '2TB',
  //       interface: 'PCIe 4.0 x4',
  //       read_speed: '7000 MB/s',
  //       write_speed: '5100 MB/s',
  //       form_factor: 'M.2 2280',
  //       endurance: '1200 TBW',
  //     },
  //     images: ['https://example.com/samsung-ssd.jpg'],
  //   },
  //   {
  //     name: 'AMD Radeon RX 7900 XTX',
  //     description: 'High-performance Graphics Card',
  //     price: 999.99,
  //     salePrice: 949.99,
  //     stock: 20,
  //     type: ProductType.GPU,
  //     categoryId: allCategories[6].id,
  //     brandId: brands[3].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       memory: '24GB GDDR6',
  //       boost_clock: '2500 MHz',
  //       stream_processors: '6144',
  //       ray_tracing: 'Yes',
  //       power_consumption: '355W',
  //       ports: '2x HDMI 2.1, 2x DisplayPort 2.1',
  //     },
  //     images: ['https://example.com/rx7900xtx.jpg'],
  //   },
  //   {
  //     name: 'Corsair RM850x',
  //     description: '850W Gold PSU',
  //     price: 149.99,
  //     salePrice: 139.99,
  //     stock: 40,
  //     type: ProductType.PSU,
  //     categoryId: allCategories[7].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       wattage: '850W',
  //       efficiency: '80+ Gold',
  //       modular: 'Fully',
  //       fan_size: '135mm',
  //       protection: 'OVP, UVP, OCP, OTP',
  //     },
  //     images: ['https://example.com/corsair-psu.jpg'],
  //   },
  //   {
  //     name: 'be quiet! Dark Power Pro 12',
  //     description: '1200W Platinum PSU',
  //     price: 299.99,
  //     salePrice: 279.99,
  //     stock: 25,
  //     type: ProductType.PSU,
  //     categoryId: allCategories[7].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       wattage: '1200W',
  //       efficiency: '80+ Platinum',
  //       modular: 'Fully',
  //       fan_size: '135mm',
  //       protection: 'OVP, UVP, OCP, OTP, SCP',
  //     },
  //     images: ['https://example.com/bequiet-psu.jpg'],
  //   },
  //   {
  //     name: 'Custom Gaming Beast PC',
  //     description: 'High-end Custom Gaming PC',
  //     price: 3499.99,
  //     salePrice: 3299.99,
  //     stock: 5,
  //     type: ProductType.CUSTOM_PC,
  //     categoryId: allCategories[17].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i9-13900K',
  //       memory: '64GB DDR5 6000MHz',
  //       storage: '2TB NVMe + 4TB HDD',
  //       graphics: 'RTX 4090 24GB',
  //       motherboard: 'ASUS ROG Maximus Z790',
  //       cooling: 'Custom Loop',
  //       case: 'Lian Li O11 Dynamic',
  //       psu: '1000W Platinum',
  //     },
  //     images: ['https://example.com/custom-pc.jpg'],
  //   },
  //   {
  //     name: 'Crucial Ballistix MAX 64GB',
  //     description: 'High-end Gaming RAM Kit',
  //     price: 329.99,
  //     salePrice: 309.99,
  //     stock: 20,
  //     type: ProductType.RAM,
  //     categoryId: allCategories[3].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       capacity: '64GB (4x16GB)',
  //       type: 'DDR4',
  //       speed: '4000MHz',
  //       latency: 'CL18',
  //       voltage: '1.35V',
  //       rgb: 'Yes',
  //     },
  //     images: ['https://example.com/crucial-ram.jpg'],
  //   },
  //   {
  //     name: 'TeamGroup T-Force Delta RGB',
  //     description: 'RGB Gaming RAM',
  //     price: 189.99,
  //     salePrice: 179.99,
  //     stock: 25,
  //     type: ProductType.RAM,
  //     categoryId: allCategories[3].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       capacity: '32GB (2x16GB)',
  //       type: 'DDR5',
  //       speed: '6400MHz',
  //       latency: 'CL32',
  //       voltage: '1.35V',
  //       rgb: 'Yes',
  //     },
  //     images: ['https://example.com/teamgroup-ram.jpg'],
  //   },
  //   {
  //     name: 'Kingston Fury Beast RGB',
  //     description: 'RGB Gaming RAM Kit',
  //     price: 159.99,
  //     salePrice: 149.99,
  //     stock: 30,
  //     type: ProductType.RAM,
  //     categoryId: allCategories[3].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       capacity: '32GB (2x16GB)',
  //       type: 'DDR4',
  //       speed: '3600MHz',
  //       latency: 'CL16',
  //       voltage: '1.35V',
  //       rgb: 'Yes',
  //     },
  //     images: ['https://example.com/kingston-ram.jpg'],
  //   },
  //   {
  //     name: 'Crucial P5 Plus 2TB',
  //     description: 'PCIe Gen4 NVMe SSD',
  //     price: 249.99,
  //     salePrice: 229.99,
  //     stock: 35,
  //     type: ProductType.SSD,
  //     categoryId: allCategories[4].id,
  //     brandId: brands[5].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       capacity: '2TB',
  //       interface: 'PCIe 4.0 x4',
  //       read_speed: '6600 MB/s',
  //       write_speed: '5000 MB/s',
  //       form_factor: 'M.2 2280',
  //       endurance: '1200 TBW',
  //     },
  //     images: ['https://example.com/crucial-ssd.jpg'],
  //   },
  //   {
  //     name: 'Sabrent Rocket 4 Plus 4TB',
  //     description: 'High-capacity NVMe SSD',
  //     price: 699.99,
  //     salePrice: 649.99,
  //     stock: 15,
  //     type: ProductType.SSD,
  //     categoryId: allCategories[4].id,
  //     brandId: brands[5].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       capacity: '4TB',
  //       interface: 'PCIe 4.0 x4',
  //       read_speed: '7100 MB/s',
  //       write_speed: '6600 MB/s',
  //       form_factor: 'M.2 2280',
  //       endurance: '3000 TBW',
  //     },
  //     images: ['https://example.com/sabrent-ssd.jpg'],
  //   },
  //   {
  //     name: 'WD Gold 18TB',
  //     description: 'Enterprise Hard Drive',
  //     price: 499.99,
  //     salePrice: 479.99,
  //     stock: 10,
  //     type: ProductType.HDD,
  //     categoryId: allCategories[4].id,
  //     brandId: brands[5].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       capacity: '18TB',
  //       form_factor: '3.5"',
  //       rpm: '7200',
  //       cache: '512MB',
  //       interface: 'SATA 6Gb/s',
  //       workload_rate: '550 TB/year',
  //     },
  //     images: ['https://example.com/wd-gold-hdd.jpg'],
  //   },
  //   {
  //     name: 'Seagate IronWolf Pro 16TB',
  //     description: 'NAS Hard Drive',
  //     price: 419.99,
  //     salePrice: 399.99,
  //     stock: 15,
  //     type: ProductType.HDD,
  //     categoryId: allCategories[4].id,
  //     brandId: brands[5].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       capacity: '16TB',
  //       form_factor: '3.5"',
  //       rpm: '7200',
  //       cache: '256MB',
  //       interface: 'SATA 6Gb/s',
  //       nas_optimized: 'Yes',
  //     },
  //     images: ['https://example.com/ironwolf-hdd.jpg'],
  //   },
  //   {
  //     name: 'Fractal Design Meshify 2',
  //     description: 'High-airflow ATX Case',
  //     price: 149.99,
  //     salePrice: 139.99,
  //     stock: 20,
  //     type: ProductType.CABINET,
  //     categoryId: allCategories[5].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       form_factor: 'ATX',
  //       side_panel: 'Tempered Glass',
  //       fans_included: 3,
  //       radiator_support: '420mm',
  //       dimensions: '542 x 240 x 474mm',
  //     },
  //     images: ['https://example.com/meshify2-case.jpg'],
  //   },
  //   {
  //     name: 'Phanteks Eclipse P500A',
  //     description: 'Premium ATX Case',
  //     price: 129.99,
  //     salePrice: 119.99,
  //     stock: 25,
  //     type: ProductType.CABINET,
  //     categoryId: allCategories[5].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       form_factor: 'ATX',
  //       side_panel: 'Tempered Glass',
  //       rgb: 'Yes',
  //       fans_included: 3,
  //       radiator_support: '360mm',
  //       dimensions: '510 x 240 x 505mm',
  //     },
  //     images: ['https://example.com/p500a-case.jpg'],
  //   },
  //   {
  //     name: 'be quiet! Silent Wings 4',
  //     description: 'Premium PC Case Fan',
  //     price: 29.99,
  //     salePrice: 24.99,
  //     stock: 50,
  //     type: ProductType.FAN,
  //     categoryId: allCategories[5].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       size: '140mm',
  //       speed: '1600 RPM',
  //       noise_level: '18.4 dBA',
  //       airflow: '103.6 CFM',
  //       pwm: 'Yes',
  //     },
  //     images: ['https://example.com/silent-wings-fan.jpg'],
  //   },
  //   {
  //     name: 'Corsair iCUE QL120',
  //     description: 'RGB Case Fan',
  //     price: 39.99,
  //     salePrice: 34.99,
  //     stock: 40,
  //     type: ProductType.FAN,
  //     categoryId: allCategories[5].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       size: '120mm',
  //       speed: '1500 RPM',
  //       noise_level: '26 dBA',
  //       rgb: 'Yes',
  //       airflow: '41.8 CFM',
  //     },
  //     images: ['https://example.com/ql120-fan.jpg'],
  //   },
  //   {
  //     name: 'Arctic P12 PWM PST',
  //     description: 'Value Performance Fan',
  //     price: 9.99,
  //     salePrice: 8.99,
  //     stock: 100,
  //     type: ProductType.FAN,
  //     categoryId: allCategories[5].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       size: '120mm',
  //       speed: '1800 RPM',
  //       noise_level: '22.5 dBA',
  //       airflow: '56.3 CFM',
  //       pwm: 'Yes',
  //     },
  //     images: ['https://example.com/arctic-p12-fan.jpg'],
  //   },
  //   {
  //     name: 'NVIDIA GeForce RTX 4090',
  //     description: 'Flagship Gaming Graphics Card',
  //     price: 1599.99,
  //     salePrice: 1549.99,
  //     stock: 10,
  //     type: ProductType.GPU,
  //     categoryId: allCategories[6].id,
  //     brandId: brands[9].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       memory: '24GB GDDR6X',
  //       boost_clock: '2520 MHz',
  //       cuda_cores: '16384',
  //       ray_tracing: 'Yes',
  //       power_consumption: '450W',
  //       ports: 'HDMI 2.1, 3x DisplayPort 1.4a',
  //     },
  //     images: ['https://example.com/rtx4090.jpg'],
  //   },
  //   {
  //     name: 'AMD Radeon RX 6950 XT',
  //     description: 'High-end Gaming Graphics Card',
  //     price: 899.99,
  //     salePrice: 849.99,
  //     stock: 15,
  //     type: ProductType.GPU,
  //     categoryId: allCategories[6].id,
  //     brandId: brands[3].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       memory: '16GB GDDR6',
  //       boost_clock: '2310 MHz',
  //       stream_processors: '5120',
  //       ray_tracing: 'Yes',
  //       power_consumption: '335W',
  //       ports: 'HDMI 2.1, 2x DisplayPort 1.4',
  //     },
  //     images: ['https://example.com/rx6950xt.jpg'],
  //   },
  //   {
  //     name: 'NVIDIA GeForce RTX 4070',
  //     description: 'Mid-range Gaming Graphics Card',
  //     price: 599.99,
  //     salePrice: 579.99,
  //     stock: 25,
  //     type: ProductType.GPU,
  //     categoryId: allCategories[6].id,
  //     brandId: brands[9].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       memory: '12GB GDDR6X',
  //       boost_clock: '2475 MHz',
  //       cuda_cores: '5888',
  //       ray_tracing: 'Yes',
  //       power_consumption: '200W',
  //       ports: 'HDMI 2.1, 3x DisplayPort 1.4a',
  //     },
  //     images: ['https://example.com/rtx4070.jpg'],
  //   },
  //   {
  //     name: 'Seasonic PRIME TX-1000',
  //     description: 'Titanium Rated PSU',
  //     price: 359.99,
  //     salePrice: 339.99,
  //     stock: 20,
  //     type: ProductType.PSU,
  //     categoryId: allCategories[7].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       wattage: '1000W',
  //       efficiency: '80+ Titanium',
  //       modular: 'Fully',
  //       fan_size: '135mm',
  //       protection: 'OVP, UVP, OCP, OTP, SCP',
  //       warranty: '12 years',
  //     },
  //     images: ['https://example.com/seasonic-psu.jpg'],
  //   },
  //   {
  //     name: 'EVGA SuperNOVA 1300 GT',
  //     description: 'High-wattage Gold PSU',
  //     price: 229.99,
  //     salePrice: 209.99,
  //     stock: 25,
  //     type: ProductType.PSU,
  //     categoryId: allCategories[7].id,
  //     brandId: brands[8].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       wattage: '1300W',
  //       efficiency: '80+ Gold',
  //       modular: 'Fully',
  //       fan_size: '140mm',
  //       protection: 'OVP, UVP, OCP, OTP, SCP',
  //     },
  //     images: ['https://example.com/evga-psu.jpg'],
  //   },
  //   {
  //     name: 'MSI MPG A850GF',
  //     description: 'Gold Rated PSU',
  //     price: 139.99,
  //     salePrice: 129.99,
  //     stock: 30,
  //     type: ProductType.PSU,
  //     categoryId: allCategories[7].id,
  //     brandId: brands[7].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       wattage: '850W',
  //       efficiency: '80+ Gold',
  //       modular: 'Fully',
  //       fan_size: '140mm',
  //       protection: 'OVP, UVP, OCP, OTP',
  //     },
  //     images: ['https://example.com/msi-psu.jpg'],
  //   },
  //   {
  //     name: 'Streaming Beast Custom PC',
  //     description: 'Streaming and Content Creation PC',
  //     price: 2999.99,
  //     salePrice: 2899.99,
  //     stock: 5,
  //     type: ProductType.CUSTOM_PC,
  //     categoryId: allCategories[17].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'AMD Ryzen 9 7950X',
  //       memory: '64GB DDR5 5600MHz',
  //       storage: '4TB NVMe + 8TB HDD',
  //       graphics: 'RTX 4080 16GB',
  //       motherboard: 'MSI MEG X670E ACE',
  //       cooling: '360mm AIO',
  //       case: 'Phanteks P500A',
  //       psu: '1000W Platinum',
  //     },
  //     images: ['https://example.com/streaming-pc.jpg'],
  //   },
  //   {
  //     name: 'Compact Gaming Custom PC',
  //     description: 'Small Form Factor Gaming PC',
  //     price: 1999.99,
  //     salePrice: 1899.99,
  //     stock: 8,
  //     type: ProductType.CUSTOM_PC,
  //     categoryId: allCategories[17].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i7-13700K',
  //       memory: '32GB DDR5 6000MHz',
  //       storage: '2TB NVMe',
  //       graphics: 'RTX 4070 Ti',
  //       motherboard: 'ASUS ROG STRIX Z690-I',
  //       cooling: '240mm AIO',
  //       case: 'NZXT H1',
  //       psu: '750W SFX Gold',
  //     },
  //     images: ['https://example.com/compact-pc.jpg'],
  //   },
  //   {
  //     name: 'Workstation Custom PC',
  //     description: 'Professional Workstation PC',
  //     price: 4499.99,
  //     salePrice: 4299.99,
  //     stock: 3,
  //     type: ProductType.CUSTOM_PC,
  //     categoryId: allCategories[17].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'AMD Threadripper 5990X',
  //       memory: '128GB DDR4 ECC',
  //       storage: '8TB NVMe + 16TB HDD',
  //       graphics: 'NVIDIA RTX A6000',
  //       motherboard: 'ASUS Pro WS WRX80E-SAGE',
  //       cooling: 'Custom Loop',
  //       case: 'Phanteks Enthoo 719',
  //       psu: '1600W Titanium',
  //     },
  //     images: ['https://example.com/workstation-pc.jpg'],
  //   },
  //   {
  //     name: 'Budget Gaming Custom PC',
  //     description: 'Value Gaming PC Build',
  //     price: 999.99,
  //     salePrice: 949.99,
  //     stock: 10,
  //     type: ProductType.CUSTOM_PC,
  //     categoryId: allCategories[17].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'AMD Ryzen 5 7600X',
  //       memory: '16GB DDR5 5200MHz',
  //       storage: '1TB NVMe',
  //       graphics: 'RTX 4060 Ti',
  //       motherboard: 'MSI B650M PRO',
  //       cooling: 'Air Cooling',
  //       case: 'Corsair 4000D Airflow',
  //       psu: '650W Gold',
  //     },
  //     images: ['https://example.com/budget-pc.jpg'],
  //   },
  //   {
  //     name: 'Razer BlackWidow V3 Pro',
  //     description: 'Wireless Mechanical Gaming Keyboard',
  //     price: 229.99,
  //     salePrice: 199.99,
  //     stock: 25,
  //     type: ProductType.KEYBOARD,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       switches: 'Razer Green',
  //       backlight: 'RGB',
  //       wireless: 'Yes',
  //       battery_life: '192 hours',
  //       palmrest: 'Detachable',
  //       multimedia: 'Yes',
  //     },
  //     images: ['https://example.com/blackwidow-keyboard.jpg'],
  //   },
  //   {
  //     name: 'Ducky One 3',
  //     description: 'Premium Mechanical Keyboard',
  //     price: 119.99,
  //     salePrice: 109.99,
  //     stock: 20,
  //     type: ProductType.KEYBOARD,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       switches: 'Cherry MX Brown',
  //       backlight: 'RGB',
  //       wireless: 'No',
  //       hot_swappable: 'Yes',
  //       keycaps: 'PBT Double-shot',
  //     },
  //     images: ['https://example.com/ducky-keyboard.jpg'],
  //   },
  //   {
  //     name: 'Keychron Q1',
  //     description: 'Custom Mechanical Keyboard',
  //     price: 169.99,
  //     salePrice: 159.99,
  //     stock: 15,
  //     type: ProductType.KEYBOARD,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       switches: 'Gateron G Pro Red',
  //       backlight: 'RGB',
  //       wireless: 'No',
  //       hot_swappable: 'Yes',
  //       case: 'Aluminum',
  //       keycaps: 'PBT Double-shot',
  //     },
  //     images: ['https://example.com/keychron-keyboard.jpg'],
  //   },
  //   {
  //     name: 'ASUS ROG Azoth',
  //     description: 'Premium Gaming Keyboard',
  //     price: 249.99,
  //     salePrice: 229.99,
  //     stock: 20,
  //     type: ProductType.KEYBOARD,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       switches: 'ROG NX Red',
  //       backlight: 'RGB Per-key',
  //       wireless: 'Yes',
  //       hot_swappable: 'Yes',
  //       oled: 'Yes',
  //       battery_life: '150 hours',
  //     },
  //     images: ['https://example.com/azoth-keyboard.jpg'],
  //   },
  //   {
  //     name: 'Logitech G Pro X Superlight',
  //     description: 'Ultra-lightweight Gaming Mouse',
  //     price: 149.99,
  //     salePrice: 129.99,
  //     stock: 30,
  //     type: ProductType.MOUSE,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       sensor: 'HERO 25K',
  //       dpi: '25600',
  //       weight: '63g',
  //       wireless: 'Yes',
  //       battery_life: '70 hours',
  //       buttons: 5,
  //     },
  //     images: ['https://example.com/superlight-mouse.jpg'],
  //   },
  //   {
  //     name: 'Glorious Model O Wireless',
  //     description: 'Lightweight Gaming Mouse',
  //     price: 79.99,
  //     salePrice: 69.99,
  //     stock: 40,
  //     type: ProductType.MOUSE,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       sensor: 'BAMF',
  //       dpi: '19000',
  //       weight: '69g',
  //       wireless: 'Yes',
  //       battery_life: '71 hours',
  //       rgb: 'Yes',
  //     },
  //     images: ['https://example.com/model-o-mouse.jpg'],
  //   },
  //   {
  //     name: 'Zowie EC2-C',
  //     description: 'Esports Gaming Mouse',
  //     price: 69.99,
  //     salePrice: 64.99,
  //     stock: 35,
  //     type: ProductType.MOUSE,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       sensor: '3360',
  //       dpi: '3200',
  //       weight: '73g',
  //       wireless: 'No',
  //       polling_rate: '1000Hz',
  //       buttons: 5,
  //     },
  //     images: ['https://example.com/ec2-mouse.jpg'],
  //   },
  //   {
  //     name: 'SteelSeries Prime Wireless',
  //     description: 'Professional Gaming Mouse',
  //     price: 129.99,
  //     salePrice: 119.99,
  //     stock: 25,
  //     type: ProductType.MOUSE,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       sensor: 'TrueMove Pro',
  //       dpi: '18000',
  //       weight: '80g',
  //       wireless: 'Yes',
  //       battery_life: '100 hours',
  //       buttons: 6,
  //     },
  //     images: ['https://example.com/prime-mouse.jpg'],
  //   },
  //   {
  //     name: 'Logitech MX Vertical',
  //     description: 'Ergonomic Wireless Mouse',
  //     price: 99.99,
  //     salePrice: 89.99,
  //     stock: 30,
  //     type: ProductType.MOUSE,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       sensor: 'Darkfield',
  //       dpi: '4000',
  //       ergonomic: 'Yes',
  //       wireless: 'Yes',
  //       battery_life: '4 months',
  //       buttons: 6,
  //     },
  //     images: ['https://example.com/mx-vertical-mouse.jpg'],
  //   },
  //   {
  //     name: 'Blue Yeti X',
  //     description: 'Professional USB Microphone',
  //     price: 169.99,
  //     salePrice: 149.99,
  //     stock: 25,
  //     type: ProductType.ACCESSORY,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       type: 'Condenser',
  //       patterns: '4 Pickup Patterns',
  //       sample_rate: '48kHz',
  //       bit_depth: '24-bit',
  //       monitoring: 'Zero-latency',
  //     },
  //     images: ['https://example.com/yeti-mic.jpg'],
  //   },
  //   {
  //     name: 'Elgato Stream Deck MK.2',
  //     description: 'Stream Control Console',
  //     price: 149.99,
  //     salePrice: 139.99,
  //     stock: 20,
  //     type: ProductType.ACCESSORY,
  //     categoryId: allCategories[2].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       keys: '15 LCD Keys',
  //       customizable: 'Yes',
  //       interface: 'USB-C',
  //       software: 'Stream Deck App',
  //       compatibility: 'Windows/Mac',
  //     },
  //     images: ['https://example.com/stream-deck.jpg'],
  //   },
  //   {
  //     name: 'Intel Core i5-13600K',
  //     description: 'Mid-range Gaming Processor',
  //     price: 319.99,
  //     salePrice: 299.99,
  //     stock: 30,
  //     type: ProductType.PROCESSOR,
  //     categoryId: allCategories[3].id,
  //     brandId: brands[4].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       cores: '14 (6P + 8E)',
  //       threads: 20,
  //       base_speed: '3.5 GHz',
  //       boost_speed: '5.1 GHz',
  //       cache: '24MB',
  //       tdp: '125W',
  //       socket: 'LGA 1700',
  //     },
  //     images: ['https://example.com/13600k.jpg'],
  //   },
  //   {
  //     name: 'AMD Ryzen 7 7800X3D',
  //     description: 'Gaming-focused Processor',
  //     price: 449.99,
  //     salePrice: 429.99,
  //     stock: 25,
  //     type: ProductType.PROCESSOR,
  //     categoryId: allCategories[3].id,
  //     brandId: brands[3].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       cores: 8,
  //       threads: 16,
  //       base_speed: '4.2 GHz',
  //       boost_speed: '5.0 GHz',
  //       cache: '104MB',
  //       tdp: '120W',
  //       socket: 'AM5',
  //     },
  //     images: ['https://example.com/7800x3d.jpg'],
  //   },
  //   {
  //     name: 'Intel Core i3-13100',
  //     description: 'Entry-level Processor',
  //     price: 149.99,
  //     salePrice: 139.99,
  //     stock: 40,
  //     type: ProductType.PROCESSOR,
  //     categoryId: allCategories[3].id,
  //     brandId: brands[4].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       cores: 4,
  //       threads: 8,
  //       base_speed: '3.4 GHz',
  //       boost_speed: '4.5 GHz',
  //       cache: '12MB',
  //       tdp: '65W',
  //       socket: 'LGA 1700',
  //     },
  //     images: ['https://example.com/13100.jpg'],
  //   },
  //   {
  //     name: 'MSI MAG B650 TOMAHAWK',
  //     description: 'Mid-range AMD Motherboard',
  //     price: 199.99,
  //     salePrice: 189.99,
  //     stock: 25,
  //     type: ProductType.MOTHERBOARD,
  //     categoryId: allCategories[4].id,
  //     brandId: brands[7].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       socket: 'AM5',
  //       form_factor: 'ATX',
  //       memory_slots: 4,
  //       max_memory: '128GB',
  //       pci_slots: '2x PCIe 4.0 x16',
  //       wifi: 'WiFi 6E',
  //     },
  //     images: ['https://example.com/b650-tomahawk.jpg'],
  //   },
  //   {
  //     name: 'ASUS TUF Gaming B760M-PLUS',
  //     description: 'Budget Intel Motherboard',
  //     price: 169.99,
  //     salePrice: 159.99,
  //     stock: 30,
  //     type: ProductType.MOTHERBOARD,
  //     categoryId: allCategories[4].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       socket: 'LGA 1700',
  //       form_factor: 'Micro-ATX',
  //       memory_slots: 4,
  //       max_memory: '128GB',
  //       pci_slots: 'PCIe 4.0 x16',
  //       wifi: 'WiFi 6',
  //     },
  //     images: ['https://example.com/b760m-tuf.jpg'],
  //   },
  //   {
  //     name: 'Gigabyte Z790 AORUS MASTER',
  //     description: 'High-end Intel Motherboard',
  //     price: 499.99,
  //     salePrice: 479.99,
  //     stock: 15,
  //     type: ProductType.MOTHERBOARD,
  //     categoryId: allCategories[4].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       socket: 'LGA 1700',
  //       form_factor: 'ATX',
  //       memory_slots: 4,
  //       max_memory: '128GB',
  //       pci_slots: '2x PCIe 5.0 x16',
  //       wifi: 'WiFi 6E',
  //     },
  //     images: ['https://example.com/z790-aorus.jpg'],
  //   },
  //   {
  //     name: 'ASRock X670E Steel Legend',
  //     description: 'Premium AMD Motherboard',
  //     price: 329.99,
  //     salePrice: 309.99,
  //     stock: 20,
  //     type: ProductType.MOTHERBOARD,
  //     categoryId: allCategories[4].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       socket: 'AM5',
  //       form_factor: 'ATX',
  //       memory_slots: 4,
  //       max_memory: '128GB',
  //       pci_slots: 'PCIe 5.0 x16',
  //       wifi: 'WiFi 6E',
  //     },
  //     images: ['https://example.com/x670e-steel.jpg'],
  //   },
  //   {
  //     name: 'Canon PIXMA G7020',
  //     description: 'MegaTank All-in-One Printer',
  //     price: 349.99,
  //     salePrice: 329.99,
  //     stock: 20,
  //     type: ProductType.PRINTER,
  //     categoryId: allCategories[15].id,
  //     brandId: brands[2].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       type: 'Inkjet',
  //       color: 'Color',
  //       ink_system: 'MegaTank',
  //       duplex: 'Automatic',
  //       connectivity: ['USB', 'WiFi', 'Ethernet'],
  //       resolution: '4800 x 1200 dpi',
  //     },
  //     images: ['https://example.com/g7020-printer.jpg'],
  //   },
  //   {
  //     name: 'HP Pavilion Gaming Desktop',
  //     description: 'Mid-range Gaming Desktop',
  //     price: 999.99,
  //     salePrice: 949.99,
  //     stock: 15,
  //     type: ProductType.DESKTOP,
  //     categoryId: allCategories[17].id,
  //     brandId: brands[0].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'AMD Ryzen 5 5600X',
  //       memory: '16GB DDR4',
  //       storage: '512GB SSD + 1TB HDD',
  //       graphics: 'RTX 3060',
  //       power_supply: '500W',
  //       os: 'Windows 11 Home',
  //     },
  //     images: ['https://example.com/pavilion-desktop.jpg'],
  //   },
  //   {
  //     name: 'Lenovo Legion Tower 5i',
  //     description: 'Gaming Desktop PC',
  //     price: 1299.99,
  //     salePrice: 1249.99,
  //     stock: 12,
  //     type: ProductType.DESKTOP,
  //     categoryId: allCategories[17].id,
  //     brandId: brands[0].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i7-12700',
  //       memory: '32GB DDR4',
  //       storage: '1TB SSD',
  //       graphics: 'RTX 3070',
  //       power_supply: '650W',
  //       os: 'Windows 11 Home',
  //     },
  //     images: ['https://example.com/legion-desktop.jpg'],
  //   },
  //   {
  //     name: 'Apple iMac 24"',
  //     description: 'All-in-One Desktop',
  //     price: 1499.99,
  //     salePrice: 1449.99,
  //     stock: 10,
  //     type: ProductType.ALL_IN_ONE,
  //     categoryId: allCategories[16].id,
  //     brandId: brands[0].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Apple M1',
  //       memory: '16GB',
  //       storage: '512GB SSD',
  //       display: '24" 4.5K Retina',
  //       camera: '1080p FaceTime HD',
  //       os: 'macOS',
  //     },
  //     images: ['https://example.com/imac-24.jpg'],
  //   },
  //   {
  //     name: 'ASUS Zen AiO 24',
  //     description: 'All-in-One PC',
  //     price: 999.99,
  //     salePrice: 949.99,
  //     stock: 15,
  //     type: ProductType.ALL_IN_ONE,
  //     categoryId: allCategories[16].id,
  //     brandId: brands[6].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i5-1240P',
  //       memory: '16GB DDR4',
  //       storage: '512GB SSD',
  //       display: '23.8" FHD Touch',
  //       graphics: 'Intel Iris Xe',
  //       os: 'Windows 11 Home',
  //     },
  //     images: ['https://example.com/zen-aio.jpg'],
  //   },
  //   {
  //     name: 'HP Envy 34" Curved',
  //     description: 'Premium Curved All-in-One',
  //     price: 1999.99,
  //     salePrice: 1899.99,
  //     stock: 8,
  //     type: ProductType.ALL_IN_ONE,
  //     categoryId: allCategories[16].id,
  //     brandId: brands[0].id,
  //     featured: true,
  //     isPublished: true,
  //     specs: {
  //       processor: 'Intel Core i7-11700',
  //       memory: '32GB DDR4',
  //       storage: '1TB SSD',
  //       display: '34" 5K Curved',
  //       graphics: 'RTX 3060',
  //       webcam: 'Detachable',
  //     },
  //     images: ['https://example.com/envy-34.jpg'],
  //   },
  // ];

  const productsData = [];

  await Promise.all(
    productsData.map(async (productDetails) => {
      const existingProduct = await prisma.product.findFirst({
        where: { name: productDetails.name },
      });

      if (!existingProduct) {
        await prisma.product.create({
          data: {
            name: productDetails.name,
            description: productDetails?.description || 'Product description',
            price: productDetails?.price || 0,
            stock: productDetails?.stock || 0,
            type: productDetails.type,
            categoryId: productDetails.categoryId,
            brandId: productDetails.brandId,
            featured: productDetails?.featured || false,
            isPublished: productDetails?.isPublished || false,
            specs: productDetails?.specs || {},
            images: productDetails?.images || [],
          },
        });
      }
    }),
  );

  console.log('Seed data created successfully');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
